### ISSUE TITLE
Add to official Casbin adapter list?

### ISSUE THREAD

**Issue by gilcrest** [pckhoi/casbin-pgx-adapter#1]
Hi @pckhoi - I'm looking for a pgx adapter for Casbin and this one looks great! Is there any reason you haven't added this to the [official adapter list](https://casbin.org/docs/en/adapters)? I see you're part of the Casbin organization, so I was wondering if this is feature complete enough to be used? Thanks so much!

**Comment by pckhoi** [comment]
Well I told Yang Luo about this repo but he hasn't responded to me so I'm not sure how he felt about it.

I did use this library for a short period of time a few months ago and at that point it had feature parity with the casbin-pg-adapter library so it is probably good enough for you.

I would actually recommend you check out my [tulip](https://github.com/pckhoi/tulip) library though as it can achieve much higher performance than using Casbin. It uses a different interface though and might be a tad harder to use but if you measure performance at all you'll love it. If you care to find out more, I'll add documentation and whatever else that make it easy to use.

**Comment by hsluoyz** [comment]
Hi @pckhoi I didn't remember that you told me about this adapter.. This adapter is quite new as only created 4 months ago.

![image](https://user-images.githubusercontent.com/3787410/145069352-5dda4ede-111a-4a0b-ae8f-a8439a41ba98.png)


Actually it looks great, why not add it? Can you add it to official list via PR to: https://github.com/casbin/casbin-website ? If you don't have time for this, I can do it too :)

**Comment by pckhoi** [comment]
@hsluoyz I sent you an email, maybe it landed in spam folder? I can open a PR. ;)

**Comment by hsluoyz** [comment]
@pckhoi maybe. I have multiple email accounts and some of them have hundreds of mails every day. So maybe it is missing somewhere :( Well, Github should be the most reliable way to find me, Gitter is also OK :)

**Comment by pckhoi** [comment]
@hsluoyz got it, sorry for not finding you in other ways. Lesson learned ;)

**Comment by hsluoyz** [comment]
Thanks! The PR has been done at: https://github.com/casbin/casbin-website/pull/293

@gilcrest plz close this ticket if everything is OK :)

**Comment by gilcrest** [comment]
Yup - looks great - thanks again!
