### ISSUE TITLE
Breaking Change in Casbin when updated from v2.54.0 to v2.68.0

### ISSUE THREAD

**Issue by MrAwanishKumar** [pckhoi/casbin-pgx-adapter#12]
Getting error when updated the casbin version to latest 

`# github.com/pckhoi/casbin-pgx-adapter
../../../../go/pkg/mod/github.com/pckhoi/casbin-pgx-adapter@v1.0.1/adapter.go:347:50: cannot use persist.LoadPolicyLine (value of type func(line string, m model.Model) error) as func(string, model.Model) value in argument to a.loadFilteredPolicy`

Although it was already discussed in #6 and by downgrading to the v2.54.0 it is working.

I am looking for fixed with latest version of casbin.

Thanks

**Comment by hsluoyz** [comment]
@MrAwanishKumar what version of Casbin and casbin-pgx-adapter are you using?

casbin-pgx-adapter v2.2.0 and later versions should already support latest versions of Casbin, see: https://github.com/pckhoi/casbin-pgx-adapter/releases/tag/v2.2.0

**Comment by pckhoi** [comment]
Maybe you can try `github.com/pckhoi/casbin-pgx-adapter/v3`. The tests seem to pass at least.

**Comment by MrAwanishKumar** [comment]
@hsluoyz earlier I was using the older version of casbin v2.54.0 and casbin-pgx-adapter v1.0.1, was working fine but when I do update, the casbin updates to v2.68.0 and casbin-pgx-adapter remain on the same version v1.0.1. This causes the issue.

Now updated the both casbin to v2.68.0 and using casbin-pgx-adapter/v3 working fine. 

Thank you @pckhoi  and @hsluoyz

**Comment by MrAwanishKumar** [comment]
Problem is solved. Closing this issue. 

Thanks
