### ISSUE TITLE
Ability to change default schema

### ISSUE THREAD

**Issue by AAZANOVICH** [pckhoi/casbin-pgx-adapter#2]
Is it possible to change default schema ? Casbin rule table is getting created on "public" schema by default. I know I can set custom db name and table name, but what about schema ?

**Comment by pckhoi** [comment]
Sure, I don't see why the schema cannot be modified. If you don't want to wait then feel free to create a PR. Otherwise, I'll try to implement this in 1 week.

**Comment by pckhoi** [comment]
Take a look at `v2.1.0`. I believe it is what you were asking for, yes?

**Comment by AAZANOVICH** [comment]
Looks like your package is not published.

go get github.com/pckhoi/casbin-pgx-adapter@v2.1.0
go get: github.com/pckhoi/casbin-pgx-adapter@v2.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

go list -m -versions github.com/pckhoi/casbin-pgx-adapter
github.com/pckhoi/casbin-pgx-adapter v1.0.0 v1.0.1

**Comment by pckhoi** [comment]
Can you try running `go get github.com/pckhoi/casbin-pgx-adapter/v2`?

**Comment by AAZANOVICH** [comment]
It works, thanks!
