### ISSUE TITLE
Ability to SavePolicy to db within specific transaction

### ISSUE THREAD

**Issue by AAZANOVICH** [pckhoi/casbin-pgx-adapter#4]
I think  it will be useful to be able to pass pgx.Tx to SavePolicy, so we can perform multiple db updates within save transaction/ or rollback all together.

**Comment by pckhoi** [comment]
I highly doubt it is even possible with how Casbin work currently but how would the code look like in your mind?

**Comment by pckhoi** [comment]
@hsluoyz What do you think?

**Comment by hsluoyz** [comment]
@tangyang9464 @jialinwang

**Comment by AAZANOVICH** [comment]
> I highly doubt it is even possible with how Casbin work currently but how would the code look like in your mind?

The way I see it, the method will have an additional argument SavePolicyTx(model model.Model, tx pgx.Tx).
Instead of acquiring a new connection from the pool within method implementation, it will just perform all operations on "tx" argument. This way consumer can start transaction i.e. 

pool.BeginTxFunc(... , func( tx pgx.Tx).. {
      ....
       adapter.SavePolicyTx(m, tx)
       myService.DoSomething(..., tx)
      ....
})

**Comment by tangyang9464** [comment]
@pckhoi @AAZANOVICH It doesn't seem feasible. Casbin.SavePolicy cannot provide a specific parameter for this adapter, it is not generic. Unless you just use adapter.SavePolicy, but to be clear, Casbin.SavePolicy is not just a simple call to adapter.SavePolicy, there will be some extra processing.

**Comment by chr1shung** [comment]
Hi I have similar use case and saw  the related discussion in https://github.com/casbin/casbin/issues/1205,  which concluded that the tx should be handled by the adapter.
Is it possible to support it now w/o updating the `Adapter` interface ?

**Comment by pckhoi** [comment]
Let's just face it. Casbin's interface still does not support transaction as of this version. It is possible to do something like this: https://github.com/casbin/gorm-adapter/issues/206. But it seems to me like a hack.

Feel free to make a fork of this repo and adapt to the same way above. But until Casbin officially support transaction, I don't think it is worth adding support.
