### ISSUE TITLE
Proper quoting of Table Name

### ISSUE THREAD

**Issue by jtwatson** [pckhoi/casbin-pgx-adapter#8]
Hello,

As best I can tell the current code does not support a table name such as `AccessPolicies`. Due to the lack of quoting, it ends up in the database as `accesspolicies`.  If I pass in quoting in the name, there is at least one place where the query errors due to the concatenation of the table name with `_pkey`. 

Are you open to a Pull Request that fixes this issue? 

To avoid a Breaking change, I think I would need to preserve the existing default not quoting a table name.  I could fix the code to handle a table name being quoted if it is provided as quoted, and/or provide a new Option that indicates the table name should be quoted `pgxadapter.WithTableNameWithQuotes()` or something simular.

Let me know your thoughts!

**Comment by pckhoi** [comment]
Thank you for the fix! Let's continue the discussion within the PR.

**Comment by pckhoi** [comment]
Fixed with version 2.2.1
